- search-parts/src/models/ISearchResult.ts
- search-parts/src/services/SearchService/MockSearchService.ts
- search-parts/src/services/SearchService/SearchService.ts
- search-parts/src/templates/layouts/default.html
- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
- search-parts/src/webparts/searchResults/components/SearchResultsContainer/ISearchResultsContainerProps.ts
- search-parts/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | n/a
Always render the inline or external 'custom' result template. This functionality enables rendering of results which only include secondary results or kick off alternate queries when the original query returned zero results.
@wobba
> Always render custom result type

- search-extensibility-library/src/libraries/CustomComponent.tsx
- search-parts/src/services/DynamicDataService/DynamicDataService.ts
- search-parts/src/services/DynamicDataService/IDynamicDataService.ts
- search-parts/src/services/SearchService/MockSearchService.ts
- search-parts/src/services/TemplateService/MockTemplateService.ts
- search-parts/src/templates/layouts/slider.html
- search-parts/src/webparts/searchPagination/SearchPaginationWebPart.ts
- search-parts/src/webparts/searchRefiners/SearchRefinersWebPart.ts
- search-parts/src/webparts/searchResults/ISearchResultsWebPartProps.ts
- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
- Fixed #31. We removed the `            this.context.dynamicDataProvider.registerAvailableSourcesChanged(this.render);` method to avoid multiple renders every time. According to [https://github.com/SharePoint/sp-dev-docs/issues/2985#issuecomment-536055289](https://github.com/SharePoint/sp-dev-docs/issues/2985#issuecomment-536055289), the DynamicProperty should wait for the wired data source and re-render the component when available so no need to to it manually anymore.
- Fixed #30 by adding relevant mock data for local workbench.
> [ModernSearch] Fixed issues #30 and #31

- search-parts/src/components/DocumentCardComponent.tsx
Here's a minor update to fix an issue regarding the height in tile views in compact mode.
Before:
After:
> Thumbnail height is incorrect

- docs/search-parts/search-results.md
- search-parts/src/services/TokenService/TokenService.ts
**Fixed:**
- Fixed #43 by adding an 'OR' operator `{|` in available tokens for page taxonomy and choice multi values columns. Added the corresponding documentation.
> [search-parts] Fixed #43

- search-parts/src/webparts/searchRefiners/components/Layouts/LinkPanel/LinkPanel.tsx
- search-parts/src/webparts/searchRefiners/components/Layouts/Vertical/Vertical.tsx
- search-parts/src/webparts/searchRefiners/components/Templates/ContainerTree/ContainerTreeTemplate.tsx
- search-parts/src/webparts/searchRefiners/components/Templates/TemplateRenderer.tsx
- Fixed #92. Now the container tree refiner template follows the _"Expand filter by default"_ option set in the associated refiner configuration.
> [search-parts] Fixed #92

- search-extensibility-library/.vscode/launch.json
- search-extensibility-library/src/libraries/myCompanyLibrary/MyCompanyLibraryLibrary.ts
- search-extensibility-library/src/models/IExtensibilityLibrary.ts
- search-parts/src/models/IQueryModifierConfiguration.ts
- search-parts/src/services/ExtensibilityService/IExtensibilityLibrary.ts
- search-parts/src/webparts/searchResults/ISearchResultsWebPartProps.ts
- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
- search-parts/src/webparts/searchResults/loc/en-us.js
- search-parts/src/webparts/searchResults/loc/es-es.js
- search-parts/src/webparts/searchResults/loc/fr-fr.js
- search-parts/src/webparts/searchResults/loc/mystrings.d.ts
- search-parts/src/webparts/searchResults/loc/nl-nl.js
Related to #97 
Added the ability to choose among multiple query modifiers. However, only one can be selected at once per Search Results WP instance.
> [search-parts] + [search-extesnbility] Added the ability to choose among multiple search query modifiers

- search-parts/src/webparts/searchRefiners/components/SearchRefinersContainer/SearchRefinersContainer.tsx
Fixed #106 - A 'map' instead of a 'filter' was used to see if a current date range refiner was selected causing a reset of the refinement count so a null rendering.
> [search-parts] Fix bug #106

- search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer/SearchVerticalsContainer.tsx
Removing placeholder (whitespace) if the icon property is empty or wrong for the search verticals
> [search-parts] [searchVerticals]: Removing white space if no icon selected  

- search-parts/src/services/SearchService/SearchService.ts
- search-parts/src/webparts/searchRefiners/components/Layouts/LinkPanel/LinkPanel.module.scss
- search-parts/src/webparts/searchRefiners/components/Layouts/LinkPanel/LinkPanel.tsx
- search-parts/src/webparts/searchRefiners/components/Templates/Checkbox/CheckboxTemplate.tsx
- search-parts/src/webparts/searchRefiners/components/Templates/DateRange/DateRangeTemplate.tsx
- search-parts/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx
Related to #129. The 'Size' managed property was not returning the correct refinement name. Now, we use the refiner name every time regardless the value returned by the API.
> [search-parts] Fixed #129

- .gitignore
- search-parts/gulpfile.js
- search-parts/package-lock.json
- search-parts/package.json
- search-parts/webpack.js
This PR doesn't add any new functionality, but it tries to improve the development speed.  
I tried to improve the performance of the default SPFx builds using different ways.   
The latest and fastest approach is the tool [spfx-fast-serve](https://github.com/s-KaiNet/spfx-fast-serve).    
I used `pnp-modern-search` solution to test performance gain and the test demonstrated significant performance improvements. Since I have the code, which speeds up serve for `pnp-modern-search` locally, I decided to push a PR, so that you can try `fast-serve` and maybe even merge the PR.   
Basically you just need to run `npm install` to restore additional dependencies and then run `npm run serve`.
> Added support for faster development with a separate webpack dev server.

- docs/search-extensibility-library/getting-started.md
- docs/search-parts/templating.md
- search-parts/.vscode/launch.json
- search-parts/package-lock.json
- search-parts/package.json
- search-parts/src/components/BaseWebComponent.ts
- search-parts/src/components/DetailsListComponent.tsx
- search-parts/src/components/DocumentCardComponent.tsx
- search-parts/src/components/LivePersonaComponent.tsx
- search-parts/src/services/TemplateService/BaseTemplateService.tsx
- search-parts/src/templates/layouts/debug.html
- search-parts/src/templates/layouts/default.html
- search-parts/src/templates/layouts/details-list.html
- search-parts/src/templates/layouts/mock.html
- search-parts/src/templates/layouts/people.html
- search-parts/src/templates/layouts/simple-list.html
- search-parts/src/templates/layouts/slider.html
- search-parts/src/templates/layouts/tiles.html
- search-parts/src/templates/resultTypes/default_list.html
- search-parts/src/templates/resultTypes/default_tile.html
- search-parts/src/webparts/searchBox/components/SearchBoxAutoComplete/SearchBoxAutoComplete.tsx
- search-parts/src/webparts/searchResults/components/Layouts/ISearchResultsTemplateProps.ts
- search-parts/src/webparts/searchResults/components/Layouts/SearchResultsTemplate.tsx
- search-parts/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx
- Added sanitization with DOMPurify for every dangerouslySetInnerHTML
- Added CSS prefixing with Web Part instance ID for custom CSS in templates. Support regular CSS rules + Media queries.
> [search-parts] Sanitized HTML in templates + CSS prefixing

- search-parts/src/webparts/searchVerticals/SearchVerticalsWebPart.ts
Hi all,
Small update regarding the default query string parameter value.
It should be decoded hence we fetch it from the URL.
Regards,
Bart
> Default search vertical decode

- search-parts/src/services/SearchService/SearchService.ts
Folders can have dots in their file name as well.
Therefore the check "is folder" should be performed before the "has dots in the filename" (thus is a file) check.
> Improved is file check for determining iconExt

- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
- search-parts/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx
Based on https://github.com/microsoft-search/pnp-modern-search/pull/183
Fix for scenario 2 of the issue https://github.com/microsoft-search/pnp-modern-search/issues/177
Fix for https://github.com/microsoft-search/pnp-modern-search/issues/197
Fix for https://github.com/microsoft-search/pnp-modern-search/issues/214
> Fix for issue clicking on page 1 resets sorting.

- search-parts/src/components/LivePersonaComponent.tsx
- search-parts/src/services/TemplateService/BaseTemplateService.tsx
Fixed mixed case of disableHover property to all lowercase.
Fixed Handlebar Partial registration for pnp-live-persona.
I know the live persona is not supported, but since the code was in the package, I wanted to fix it to work.  This is my first pull request so let me know if I did something wrong.
> Fixed live Persona Web Component

- docs/search-parts/search-pagination.md
- search-extensibility-library/src/models/BaseWebComponent.ts
- search-parts/src/templates/layouts/default.html
The __BaseWebComponent__._resolveAttributes_ method was not considering that now the attributes must start by _data-*_
Custom renderer Layout template updated also with data- (some doc updated too)
> BaseWebComponent in Extensibility Lib was not considering data-*

- search-parts/src/services/SearchService/SearchService.ts
Added support for Custom Results array on Secondary results
Followed the example for RelevantResults and put in results from the CustomResults array if filled for SecondaryResults.
> 226 Enhancement for Secondary Results

- search-parts/src/components/BaseWebComponent.ts
- search-parts/src/templates/layouts/details-list.html
- search-parts/src/webparts/searchResults/components/Layouts/SearchResultsTemplate.tsx
Fixed issue #232. Now, we allow all custom attributes format (with or without `data-` prefix).
> [search-parts] Fixed #232

- search-parts/src/webparts/searchRefiners/components/Templates/Checkbox/CheckboxTemplate.tsx
- search-parts/src/webparts/searchRefiners/components/Templates/FileType/FileTypeTemplate.tsx
- search-parts/src/webparts/searchRefiners/components/Templates/Persona/PersonaTemplate.tsx
Small update on refiner options filter to always display selected options, even if they do not match the filtering text specified in the text box by the user
> Persist selected values when filtering refiner options

- search-custom-renderer/src/services/ResultService/ResultService.ts
Sets the global scope variable as an array in cases where **getRegisteredRenderers** is called before **registerRenderer**. Fixes race condition as global scope object variables share mutations.
> Issue-264: Race condition while registering / loading custom renderers

- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
**Problem**
This leads to having all labels in e.g. de-DE (set in SPO -> CurrentUiCulture)) but the search query is run in eg. en-US (set in Windows -> CurrentCulture).
This leads to no search results if I search for TaxFieldManagedProperty:"GermanLabel".
**Explanation**
Search query should be sent with CurrentUiCulture. In my case it would be 1031 (de-DE) but instead 1033 (en-US) is used.
**Info**
Documentation suggests using CurrentUiCulture as well: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/localize-web-parts#localize-the-web-part-manifest
And if I searched for other uses of CurrentCulture, I couldn't find another one in the project.
> CurrentCulture is used instead of CurrentUiCulture

- search-parts/src/webparts/searchBox/loc/en-us.js
Fixed a subtle grammatical error in the search box suggestions.
"Others have search for" should be "Others have search**ed** for"
> Grammatical error in the search box suggestions

- search-parts/src/services/TemplateService/BaseTemplateService.tsx
- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
- search-parts/src/webparts/searchResults/components/Layouts/SearchResultsTemplate.tsx
Fix #316
The idea is to register partials for each webpart instances.
The original `resultTypes` partial is replaced by a new one that rely on a helper that takes instance ID of the WebPart to select the actual partial to use.
The fix works in my case (a page with two search results webparts. One result type rule for one of the two). This should be reviewed I guess.
Hope that helped
> Isolate result types rules for each webart instance

- docs/search-parts/templating.md
- search-parts/src/components/IconComponent.tsx
Added the ability to set pnp-fabric-icon error image.
The error image can be used when the url passed to data-image-url fails to load. It does not work in scenarios where a data-icon-name is passed as the onLoadingStateChange callback is not fired.
As this is an enhancement please feel free to reject.
> Added ability to set pnp-fabric-icon error image

- search-parts/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx
This makes the text colour of the web part title change appropriately when the section background changes.
See: https://github.com/microsoft-search/pnp-modern-search/issues/617
Note: the font styling (font-weight) has been updated in the latest version of sp-dev-fx-controls-react to match OOTB, but the version number diff is way off so a lot of testing needed before updating that dependency. This PR solely address the colour change issue for section backgrounds.
> Added theme variant to Web Part Title

- search-parts/src/dataSources/MicrosoftSearchDataSource.ts
When testing out Microsoft Search with a ServiceNow connector, the query succeeded in pulling data, but failed when evaluating the response payload. Using my connector, the Graph query's result payload has no aggregations specified so that doesn't exist on the object at all. The code attempts to map aggregations in MicrosoftSearchDataSource.ts, which fails.
Fixed it by adding a check and only mapping aggregations if they exist on the response Graph query's payload.
Thanks!
> Fix mapping attempt of missing aggregations on Graph objects

- search-parts/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx
Added a `scrollIntoView`, so that when you navigate pages the top of the results goes to the top of the view, if necessary.
See issue: https://github.com/microsoft-search/pnp-modern-search/issues/708
> Issue 708 scrolling into view

- search-parts/src/components/PanelComponent.tsx
- search-parts/src/webparts/searchBox/SearchBoxWebPart.ts
Fixed #705. The custom suggestion providers were not initialized correctly resulting to a wrong property bag state.
> Fixed #705

- search-parts/src/layouts/results/detailsList/DetailListLayout.ts
Typo in the "groupsCollapsed" property name during initialization.
> Fixed #699

- docs/how-to-contribute.md
Trying to re-build locally, I seemed to be missing the step to run npm install on search-parts - otherwise, getting an error (gulp not installed)
> Add npm install on search-parts (after npm link)

- search-parts/src/helpers/ObjectHelper.ts
> Fixed `Object.byPath` method to always return a string

- search-parts/src/loc/commonStrings.d.ts
- search-parts/src/loc/da-dk.js
- search-parts/src/loc/en-us.js
- search-parts/src/webparts/searchBox/loc/da-dk.js
- search-parts/src/webparts/searchResults/loc/da-dk.js
- search-parts/src/webparts/searchResults/loc/en-us.js
- search-parts/src/webparts/searchResults/loc/mystrings.d.ts
I found some inconsistencies in localization resource files - some labels were removed, some migrated to new nodes, one label was missing. This PR fixes all that issues.   
To summarize the changes: 
- _commonStrings.d.ts_:
- `Sort.SortableFieldManagedPropertyField` and `Sort.SortableFieldDisplayValueField` are not used anymore in solution (they are missing in corresponding `{locale}.js` files and no usages were found). So I removed them altogether from `commonStrings.d.ts`
- `DetailsList.SupportHTMLColumnLabel` is not found in `commonStrings.d.ts`, so I removed corresponding properties from `{locale}.js` files
- _searchResults/loc/mystrings.d.ts_:
- `LayoutPage.ManageDetailsListColumnLabel` was moved to the `common.d.ts` localization files, thus I removed this definition
- …
> Fixed problems with localization resource files

- search-parts/src/layouts/resultTypes/default_simple_list.html
- search-parts/src/layouts/results/simpleList/simple-list.html
A `div` was missing for the `{{getSummary}}` helper in the simple and default list templates causing an incorrect formatting.
> Fixed #933

- search-parts/src/services/tokenService/TokenService.ts
Fix #803.
Only Edge is repaired. IE 11 wasn't targeted
> fix regex in tokenservice.ts that broke legacy edge. Fix #803

- search-parts/src/loc/sv-SE.js
- search-parts/src/webparts/searchResults/loc/sv-SE.js
I noticed some labels in Swedish localization were obsolete and removed them in order to maintain consistency across resource files.
> Fixed small issues in Swedish resource files

- search-parts/src/services/UserService/IUserService.ts
- search-parts/src/webparts/searchRefiners/components/Templates/Persona/PersonaTemplate.tsx
Fix #1008 
Only load details of users that don't have display name, instead of loading details for all users. Update array of users with retrieved display name
> Only load persona card details if required

- search-parts/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx
- search-parts/src/webparts/searchResults/components/SortPanel/SortPanel.tsx
After a re-sort has been done in a result web part, it can now be undone.
1.) Configure additional sorting in the result web part
2.) Select the term in the drop down
3.) Now a cross appears next to the drop down box to remove the custom sorting
> Clear sorting

- search-parts/package.json
- search-parts/src/helpers/UrlHelper.ts
- search-parts/src/services/templateService/TemplateService.ts
The documentation was referencing a Handlebars helper that didn't exist in the code.
> #1083 Added missing Handlebars helper 'getGraphPreviewUrl'

- docs/how-to-contribute.md
Take into account the @wobba comment https://github.com/microsoft-search/pnp-modern-search/issues/725#issuecomment-861607406.
The `@pnp/modern-search-extensibility` is an npm reference into the `search-parts` and `search-extensibility-demo` projects. Not no need to link the project locally except if some changes are made to it.
But, be aware about any change on `@pnp/modern-search-extensibility` is critical.
> fix(doc): update contribution documentation

- docs/scenarios/includes/deployment-note.md
- docs/scenarios/page-with-filters.md
Fixed links i found when running mkdocs
WARNING  -  Documentation file 'scenarios/page-with-filters.md' contains a link to 'usage/search-filters\index.md' which is not found in the documentation files.
WARNING  -  Documentation file 'scenarios/includes/deployment-note.md' contains a link to 'scenarios/installation.md' which is not found in the documentation files.
> Per ove url fixes

- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
SearchRefiners: Unwanted filters checked when using filters in URL #1085
If RefinementToken doesn't contains ǂǂ, then it could means that the provided condition in URL is an FQL expression
> SearchRefiners: Unwanted filters checked when using filters in URL #1085

- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
Added a condition to only reset data source data in display mode.
> Fixed #1124 - Data source field is empty while editing result types for Pnp Search Results webpart

- search-parts/src/webparts/searchRefiners/components/Templates/ContainerTree/ContainerTreeTemplate.tsx
Re-encode the refinement token to make sure it corresponds to the actual path. Sometimes, when the path is too long, the SharePoint search will return a truncated refinement token value resulting to empty results.
> [v3] Fixed an issue in the Tree Container filter template

- search-parts/package.json
- search-parts/src/components/PersonaComponent.tsx
- search-parts/src/components/PersonaShimmersComponent.tsx
- search-parts/src/services/templateService/TemplateService.ts
- search-parts/src/webparts/searchBox/components/SearchBoxContainer.tsx
- search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer.tsx
Removed unecessary ITheme references from @uifabric/styling. Replace by the ITheme in office ui fabric package + fix warnings messages due to multiple file type icons load in the template service.
> Fixed warning messages due to multiple file type icons load in the template service

- search-parts/src/webparts/searchBox/loc/nl-nl.js
- search-parts/src/webparts/searchFilters/loc/nl-nl.js
- search-parts/src/webparts/searchResults/loc/nl-nl.js
- search-parts/src/webparts/searchVerticals/loc/nl-nl.js
Added nl-nl translation for key _'ImportExport'_ as this key was missing from nl-nl.js in webpart translation files.
tested by
- Adding updated solution package to dev tenant
- Adding the PnP webparts to page on sitecollection with nl-nl language setting
- Checking if the texts displayed in the webpart UI
- Checking if the webparts still function, separately and in coorperation
- finally checking the same points for the the webpart on en-US site
> added ImportExport nl-nl translation

- search-parts/src/webparts/searchResults/loc/da-dk.js
- search-parts/src/webparts/searchResults/loc/en-us.js
- search-parts/src/webparts/searchResults/loc/fr-fr.js
- search-parts/src/webparts/searchResults/loc/nl-nl.js
- search-parts/src/webparts/searchResults/loc/sv-SE.js
`{searchQueryText}` no longer works but is still used in the hover message as a tip.  
`Use the {searchQueryText} token in your data source to retrieve this value`  
new value that does work is `{inputQueryText}`  
Example:  
`Path:https://tenant.sharepoint.com/sites/sitename/Lists/listname/* AND ListItemID:{inputQueryText}`
Files updated in the following location:  
- Search-parts/src/webparts/searchResults/loc/*
> Use input query text Hover Message update

- search-parts/src/dataSources/SharePointSearchDataSource.ts
**Background:** 
if the same term is used on different sites with different default language the indexed taxid property value contains the  translation of that site collection default language and therefore it comes back as different values meaning the same with the same id but causing separate filters.
Example: 
'L0|#a2cf1afb-44b6-4cf4-bf37-642bb2e9bff3|Food' from an enlish site and 
'L0|#a2cf1afb-44b6-4cf4-bf37-642bb2e9bff3|Nahrung' from a german site.
**Solution**
We strip the language specific part of the term and use the GP0 value as the filter value (which is the tokenid only) and use also the striped value as the new term/key...
--> 'GP0|#a2cf1afb-44b6-4cf4-bf37-642bb2e9bff3' instead of 'L0|#a2cf1afb-44b6-4cf4-bf37-642bb2e9bff3|Category 1'                         --> …
> Fix/Normalisation for Taxonomy Refiner Localisation

- docs/assets/extra.css
- docs/build-the-doc.md
- docs/usage/search-results/tokens.md
- mkdocs.yml
- Updated to mkdocs 1.2.2 and mkdocs-material 7.2.4
- Removed verticals tokens as they are not implemented.
> [Documentation] Fixed #1201

- search-parts/src/webparts/searchBox/components/SearchBoxContainer.tsx
Changed line 93 on SearchBoxContainer.tsx to use queryText instead of urlEncodedQueryText that caused double encoding on queryText.
> Fixed #1236: Double encoding for queryText in Search Box

- search-parts/tsconfig.json
I noticed that `npm run serve` no longer works with the recent changes to `tsconfig.json`, especially the `target` property (ESNext). 
Accroding to the [docs](https://www.typescriptlang.org/tsconfig#target):   
> The special `ESNext` value refers to the highest version your version of TypeScript supports. This setting should be used with caution, since it doesn’t mean the same thing between different TypeScript versions and can make upgrades less predictable.  
My suggestion is to use `ES6` instead, because it's fully implemented by all browsers and it's enough to get rid of IE (produces much cleaner output with `class` etc. I guess that was the goal of changing `target`). Also, it fixes `npm run serve` issue (which is quite difficult to track down with the `ESNext` target).
> Changed TS target to ES6.

- docs/extensibility/templating.md
- search-parts/src/services/templateService/TemplateService.ts
this PR would include an index in the handlebars getAttachments helper function. - this provides functionality more like #each to be available.
> update getAttachments handlebars helper code to include index 

- search-parts/src/helpers/StringHelper.ts
- search-parts/src/services/tokenService/TokenService.ts
- Updated the token resolution logic to use an escaped Regex instead of raw string if the case it contains special characters
- Added the '{&' operator to create AND KQL queries with comma delimited strings
> Updated the token resolution logic to use an escaped Regex

- search-parts/src/models/dynamicData/IDataResultSourceData.ts
- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
as discussed in https://github.com/microsoft-search/pnp-modern-search/discussions/1577 i added the count of items to the getPropertyValue "dynamic data interface".
Tested the call and it worked well.
> Extend getPropertyValue return value by itemCount 

- search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer.module.scss
I removed the :hover statement from the SearchVerticalsContainer.module.css file to ensure the hover acts according to the theme on dark section backgrounds.
> Fix for #1584 ... Search Verticals Web Part Hover Issue on Dark Section Background

- search-parts/src/webparts/searchBox/SearchBoxWebPart.ts
- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
Fixed an issue with page hyperlinks once the Search box WP and Search Results are loaded on the same page and the search box uses query string parameter or search query. window.history.pushShate method is update twice causing default SharePoint to break.
> Fixed `window.history.pushState` updated twice causing default SharePoint links to break

- search-parts/src/services/templateService/TemplateService.ts
the getSummary handlebar helper did not filter out ID strings from hitHighlightedSummary, resulting in summaries low legibility. Like this:
Added a regex to remove all occurances of /\w+-\w+-\w+-\w+-\w+/ to the getSummary helper.
> Remove ID strings from highlighted summaries

- search-parts/src/webparts/searchBox/components/SearchBoxAutoComplete/SearchBoxAutoComplete.tsx
In case, when you are writing slowly search input value, in combination with slow async suggestion provider, method updateQuerySuggestions is triggered multiple times (previous execution is not yet finished). Result is that suggestions are duplicated. 
Proposed solution will wait for condition: inputValue is the same as searchInputValue and skip the state, when termToSuggestFrom is empty. I don't understand exactly, why condition !termToSuggestFrom has been in line 168.
> Fix duplicities in proposed suggestions

- search-parts/src/helpers/UrlHelper.ts
Currently there is a bug in the filters webpart when the search box is connected to the URL fragment. The search terms are always reflected in the URL hash, but when filters are applied, the deep link added to the URL does not respect the hash, and is instead appended after it. This results in the entire filters deep link being considered part of the search terms, and it breaks your search.
This PR ensures that the hash is always at the end of the new URL when filters are added/removed.
> Ensure URL hash is always at the end of the string

- search-parts/src/dataSources/MicrosoftSearchDataSource.ts
- Added more default fields for Microsoft Search data source to cover all entity types.
- Updated property pane fields to show the 'Selected fields' for all entity types + Reorganized fields.
> [Microsoft Search] Updated property pane fields to match API capabilities

- search-parts/src/dataSources/SharePointSearchDataSource.ts
- search-parts/src/layouts/results/people/people.html
- Render MGT component only if the user id is not empty.
- Update SharePoint data source slot **PersonQuery** to use the managed property `AADObjectID` (more reliable)
> Fixed #1675

- docs/usage/search-filters/index.md
- search-parts/src/dataSources/SharePointSearchDataSource.ts
- Fixed an issue regarding taxonomy label translations. Refiners coming from formatted property bag properties (ex: L0|#<termid>) or 'owstaxidmetadataalltagsinfo' managed property were not translated correctly.
> Taxonomy refiners translations fix

- search-parts/src/components/filters/FilterSearchBoxComponent.module.scss
- search-parts/src/components/filters/FilterSearchBoxComponent.tsx
Selected filter tags that are really long will overflow the container. This PR fixes that so they don't exceed the size of the container and the ellipsis overflow is correctly applied.
So it goes from this:
To this:
Thanks!
> Fix selected filter tags from overflowing

- search-parts/src/controls/PropertyPaneNonReactiveTextField/IPropertyPaneNonReactiveTextFieldProps.ts
- search-parts/src/controls/PropertyPaneNonReactiveTextField/PropertyPaneNonReactiveTextField.ts
- search-parts/src/controls/PropertyPaneNonReactiveTextField/components/INonReactiveTextFieldProps.ts
- search-parts/src/controls/PropertyPaneNonReactiveTextField/components/NonReactiveTextField.tsx
- search-parts/src/dataSources/MicrosoftSearchDataSource.ts
- search-parts/src/dataSources/SharePointSearchDataSource.ts
- Fixed an issue regarding the query template property pane field. The value wasn't reset after switching the data sourc due to missing key on the underlying React component.
> Query template field value persistence fix

- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
- Fixed an issue where the `{inputQueryText}` token was resolved as 'undefined' if empty and treated as a literal expression in query template.Now initialized as an empty string.
> Fixed `{inputQueryText}` token initialization

- search-parts/src/components/PersonaComponent.tsx
Issue mentioned in https://github.com/microsoft-search/pnp-modern-search/issues/1623
If PersonaComponent is used, domPurify removes the style component in the template after first paging event or new search.
After removal of the FORBID_TAGS:['style'] config line the issue is fixed.
It still is a mystery to me why this bug occurs. I think the bug iteself is on a higher level, so actually what you guys want is to purify everything that the component renders but it actually purifies the html code surrounding the component as well.
Probably "someone ;-)" needs to check if this works as you guys intended because the generel usage of dompurify is equal in all components - so it works but actually does more than it should?
> Removed forbid_tags (style) from dompurify - PersonaComponent

- search-parts/src/dataSources/SharePointSearchDataSource.ts
Enclosed refinement filters 'or' conditions values with the FQL string() operator to avoid incorrect results.
> Fixed #1797

- search-parts/src/dataSources/SharePointSearchDataSource.ts
Only enclosed term text valuw with the string() operator. Other values remain HEX encoded
>  - Fixed #1797

- search-parts/gulpfile.js
- search-parts/src/helpers/DateHelper.ts
- Momentjs locale files now included in production bundle.
- Fixed several languages in momentjs that are using two letter file name (nb-NO, es-es,...) instead SP ISO format. 
- This PR should close [this](https://github.com/microsoft-search/pnp-modern-search/issues/1372) as it's working with 'es-es'.
> Fix momentjs locale

- search-parts/src/helpers/DateHelper.ts
Hi,
Somehow i missed the necessary moment.js locale setting for de.
Moment tries to load de-de.js, (as sp local is de-de) but we have only the "de.js".
Due to this bug german users won't be able to use the new version! 
So I guess a hotfix is necessary.
Sorry should have tested that.
> [Urgent - Hotfix required] Added moment  transformation  de-de => de for locale.js

- search-parts/src/services/templateService/TemplateService.ts
Udpdating the result types Handlebars expression to use the `slot` function and handle complex property paths (like resource."@odata.type").
> Fixed #2080 . 

- search-parts/src/components/filters/FilterComboBoxComponent.tsx
Now the filter combo box values list is not re rendered when a filtered value is selected allowing to select multiple values consecutively.
> Fixed #2031

- search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer.tsx
See [#2059](https://github.com/microsoft-search/pnp-modern-search/issues/2059)
**To test the solution:**
- Create 2 pages in a SharePoint site collection
- Add the PnP -Search Verticals web part to each
- In one page, configure 2 verticals, one for each page
- The verticals should be hyperlinks
- The hyperlink should be configured to open on the current tab
- Copy the settings from the web part and apply them on the second page
- Publish both pages
- Click on the tabs. Only the content area should refresh
> Support SharePoint soft navigation

- search-parts/src/dataSources/SharePointSearchDataSource.ts
The combination that seems to work in every case seems to be `or(${termFilterWithoutTranslations},${termTextFilter})` without the HEX encoding and skipping the original value with language specific label.
> Fixed #2072

- search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer.tsx
Added a check on the vertical tab hyperlink if the search box query is empty and pass an empty string instead of `undefined`.
> Fixed #2130

- search-parts/src/components/DocumentCardComponent.tsx
- search-parts/src/layouts/results/simpleList/simple-list.html
- search-parts/src/services/templateService/TemplateService.ts
Use of the `data-selection-disabled="true"` attribute accordin to the Office UI Fluent documentation https://developer.microsoft.com/en-us/fluentui#/controls/web/selection
> Fixed #2151 - Fixed preview pane for 'List' and 'Cards' layouts when item selection is enabled

- search-parts/src/webparts/searchFilters/components/SearchFiltersContainer.tsx
Filter params are not taken into account when navigating to a search result page when the page is only partially refreshed
> Fixed #2153

- search-parts/src/components/DetailsListComponent.tsx
#2170 
updated Details List component not to use rowheader role by default. See attached issue for more detail
> rowheader default changed to false

- search-parts/src/webparts/searchResults/components/SearchResultsContainer.tsx
This PR restores a [fix made in v3](https://github.com/microsoft-search/pnp-modern-search/pull/709) of the Modern Search web parts.
When navigating through the pages of results, the view will scroll to the top of the search web part if not in the viewport.
> Scroll to view top of results

- search-parts/.vscode/launch.json
- search-parts/src/dataSources/SharePointSearchDataSource.ts
Fixed a filtering issue when localization was enabled by adding a '0' as prefix for L0|# values used by the owstaxidmetadataalltagsinfo managed property.
> Fixed #2212 regarding localization flag and owstaxidmetadataalltagsinfo managed property

- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
This PR contains a fix for an issue that occurs after having a input query text assigned and then disabling it and the query text will still be sent.
Steps to reproduce:
1. Add a search results webpart to a page
2. Configure it with SharePoint Data Source
3. Enable "Use input query text" and assign a static value query text
4. Disable "Use input query text" and you will see that the assigned static value is still used in the query
This PR makes sure that the assigned static value is not sent if disabled but there is still no way of resetting back to a "null" static value which I think should be possible. One way of resolving this would be to set the property as not required and instead do a check so that a null value would not be used in the query. I can do a PR for this also if you agree …
> Fix to not use input query text after disabling

- search-parts/src/controls/TemplateRenderer/TemplateRenderer.tsx
Update template when inputQuery changes, regardless if data stays the same!
See #2461
> Fix: Rerender on empty results when inputQuery changes

- docs/installation.md
- search-parts/config/package-solution.json
- search-parts/src/dataSources/MicrosoftSearchDataSource.ts
Bookmark & Acronym work fine so far...
Bookmark & Acronym don't work together with Entity "DriveItem".
Some Properties have to be restricted when using Bookmark & Acronym, like "from" (Paging)... Those restrictions can be applied later?
Shouldn't we limit choosing those new Entity Types (Bookmark, Acronym, chatMessage...) to be only available if the "Use beta endpoint" switch is on? 
I would do this in another PR.
Althoug I don't know if those lists are up to date:
[1.0](https://learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-1.0&preserve-view=true#scope-search-based-on-entity-types)
[beta](https://learn.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&preserve-view=true#scope-search-based-on-entity-types)
|Entity|1.0|Beta| …
> Beta Entity Types Bookmark & Acronym

- search-parts/package.json
Looks like it maybe was accidentally overwritten with merge of 1.15 branch.
> Add "semver": "7.3.5" back

- docs/extensibility/custom_data_sources.md
- docs/extensibility/index.md
- docs/index.md
- search-extensibility/src/models/IExtensibilityLibrary.ts
- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
Enables custom data source extensibility as discussed in #2397.
Also includes documentation for the feature.
A separate PR with example usage has been submitted to [https://github.com/microsoft-search/pnp-modern-search-extensibility-samples](https://github.com/microsoft-search/pnp-modern-search-extensibility-samples).
> Enable custom data source extensibility

- search-parts/src/components/PaginationComponent.module.scss
Currently the "PnP Search Results" component does not work correctly in MS Teams Desktop and MS Teams Web because when clicking on the pagination buttons, they do not work. This small change in the css resolves that error.
This commit resolves error [#2644](https://github.com/microsoft-search/pnp-modern-search/issues/2644)
> 2644: Bug fix to allow the search results WebPart use the pagination buttons in MS Teams APP and MS Teams Web

- docs/extensibility/templating.md
Corrects the documentation for the ```data-selection-all-toggle``` property. The Fluent UI documentation is also incorrect on this, see [code](https://github.com/microsoft/fluentui/blob/4afa85e9437c0ccdf33cdccce48f5b3aa8da138a/packages/react/src/utilities/selection/SelectionZone.tsx#L40).
> Correct data-selection-all-toggle documentation

- search-parts/src/components/DetailsListComponent.tsx
There is an issue with how the SelectionZone in the search results container is implemented together with the DetailsList internal selection handling. Clicking Select All in the DetailsList selects all items in the list but does not update selectedKeys in the templateContext.
This is also the issue behind #2289 so that should also be fixed after this.
This fix adds the ```data-selection-all-toggle=true``` property to the div element containing the Select All button which makes the search results container SelectionZone also trigger on the button click.
> Fix for Select All button in DetailsList

- search-parts/src/components/PaginationComponent.module.scss
As there were many pages with 3 or 4 digit numbers in MS Teams Mobile, the numbers at the end were not displayed, so they have been moved down to the next row.
For example: << < 281 282 282 283 284 .... 290 ... 310 > >> in Teams Mobile was cut off and you could not click on 310 for example.
With this solution in MS Teams Mobile it will be: 
<< < 281 282 283 284 ...
290 ...301 ..
310 > >>
BUG:
Solution:
> BUG: Fixed paging error in "MS Teams Mobile".

- docs/scenarios/Create-a-useful-People-Search.md
Added a handfull of additional queries
> Updated Create-a-useful-People-Search.md

- .github/ISSUE_TEMPLATE/bug_report.md
This fix is for the bug explained here: https://github.com/microsoft-search/pnp-modern-search/issues/2624
> #2624: Bug fix to unhide disappearing filters without page refresh

- search-parts/package.json
Fix for #2842 
Addresses the the following security vulnerabilities reported by Whitesource:
https://1drv.ms/x/s!An0A9oJjn3HHgc9seQL41IDZO4jrBw?e=JF2CgN
> Address vulnerabilities identified by Whitesource

- search-parts/src/controls/PropertyPaneAsyncCombo/components/AsyncCombo.tsx
Fix for an issue that appears when removing a row from the layout slots settings dialog. When removing a row from the layout slots settings dialog the names are shifted upwards but the field drop-downs are not shifted upwards which makes the layout slots look mismatched even though they are saved correctly when clicking Save. This fix makes the drop-downs update correctly.
> Fix for layout slots settings dialog

- search-parts/src/services/templateService/TemplateService.ts
Updated the Regex expression to allow for 2-63 octets. As I understand it, 63 octets is the max per label according to RFC 1034 but I'm not very familiar with Regex so please let me know if the change is feasible.
#2933
> Fix tld length

- search-parts/src/helpers/DateHelper.ts
When the URL of a web page contains a doc library with a two letter code that is not an ISO code supported by moment (sites/site-name/SitePages/xx/Page.aspx or sites/site-name/SitePages/aa/Page.aspx), the search web parts on this page would show empty.
> Fix for web part showing empty when URL has two letter code

- search-parts/src/webparts/searchFilters/components/SearchFiltersContainer.tsx
This bug happened due to the regression of #2624
> #3157: Bugfix Filters read from url are not set in the filter web part

- search-parts/src/helpers/LocalizationHelper.ts
https://github.com/microsoft-search/pnp-modern-search/pull/3187
In my solution, I noticed that the parseFloat part could return incorrect values, and I reorganized it as follows:
parseFloat("1s"); //output: 1
parseFloat("1hello"); //output: 1
Number("1s") //output: NaN
Number("1hello"); //output: NaN
I'm sorry for this, it slipped my mind.
> parseFloat to Number

- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
Fixes #3197
This fix changes the logic to set the original token value undefined for searchTerms if you clear your search box and thus inputQueryText is falsy.
> Fix searchTerms after clearing search box

- search-parts/src/dataSources/MicrosoftSearchDataSource.ts
Hi Team , sort enabled in property pane for external items for Microsoft Search , 
this is tested for external items .
from MS docs >>  https://learn.microsoft.com/en-us/graph/search-concept-sort >> Sorting is also supported for [external items](https://learn.microsoft.com/en-us/graph/api/resources/externalconnectors-externalitem). The [property](https://learn.microsoft.com/en-us/graph/api/resources/externalconnectors-property) of external items to be sorted on should be refinable in the search schema.
> Enable sort option for external items Microsoft Search

- search-parts/src/webparts/searchBox/components/SearchBoxAutoComplete/SearchBoxAutoComplete.tsx
- search-parts/src/webparts/searchBox/components/SearchBoxContainer.tsx
There is an issue with the search box web part, where the magnifying glass icon is not visible on dark section backgrounds. This seems to be related to the fact that it's configured to adapt to the theme (and inversion if section background is dark), even though the search box is always matted on the white background.
To fix, I removed the theme property, which assumes the text input will always have a white background on it and therefore the magnifying glass icon doesn't have to change with theme inversion when section background is set to Strong.
With theme property removed from Fluent SearchBox instances:
> Fix search box icon on strong section backgrounds

- search-parts/src/dataSources/MicrosoftSearchDataSource.ts
- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
Both 'queryString' and 'queryTemplate' in search query request contain the same data. This leads to wrong result sets. Graph Api now supports both properties with API v1.0. If correctly implemented, the result set is in accordance to search in graph explorer.
Having fixed the token replacement, the query part looks as follows:
see also Graph API [docu ](https://learn.microsoft.com/en-us/graph/api/search-query?view=graph-rest-1.0&tabs=http#example-2-basic-call-to-use-querytemplate)
> Proper support of query template in Microsoft Search

- search-parts/src/webparts/searchResults/components/SearchResultsContainer.tsx
Added a check if images are delivered by a Microsoft public CDN (M365 stock image library) or by the public CDN at the tenant level.
#3711
> Fix for #3711

- search-parts/src/components/DetailsListComponent.tsx
This should fix #3839.
As sorting by the user is only possible for one column at a time, a sort arrow is only displayed in the column according to which the search result is currently sorted.
> Fix for displaying Details List sort arrows on multiple columns

- search-parts/src/webparts/searchVerticals/SearchVerticalsWebPart.ts
This should fix #3879.
According to @wobba and @patrikhellgren my idea was to obtain a MS Graph Access Token before actually calling the API and check if it contains all necessary Scopes required for calling `/me/getMemberGroups`.
> Fix for verticals audience membership check

- .github/workflows/release.yml
- search-parts/src/services/templateService/TemplateService.ts
This should fix https://github.com/microsoft-search/pnp-modern-search/issues/3916
The updated regex is from the [HMTL standard](https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address)
I have tested out the following email addresses and it is returned by the template helper:
- `franck.cornu@contoso.onmicrosoft.com|Franck Cornu | 693A30232E667C6D656D626572736869707C6672616E636B2E636F726E7540616571756F736465762E6F6E6D6963726F736F66742E636F6D i:0#.f|membership|franck.cornu@contoso.onmicrosoft.com`
- `franck.cornu@contoso.onmicrosoft.com`
- `test.firstname+lastname@domain.com`
- `franck.c'ornu@contoso.onmicrosoft.com`
- `123456789test@domain.com`
- `test@dom-ain.com`
> Fix for getUserEmail when a email address contains a single quote

- search-parts/src/components/DownloadSelectedItemsButtonComponent.tsx
Fixes an issue that made the download button disappear when having selected one or more items and then switching page in the results view.
> Fix selection handling for download button

- search-parts/src/dataSources/SharePointSearchDataSource.ts
- search-parts/src/layouts/results/cards/CardsLayout.ts
- search-parts/src/layouts/results/simpleList/simple-list.html
handles Change to tag display in templates "breaks" existing PnP Search Results Web Parts #4039
> update Localized Metadata separator to | rather than a comma as labels might contain a comma. Updated Card and List layout to handle this update

- search-parts/src/components/DetailsListComponent.tsx
- search-parts/src/webparts/searchResults/components/SearchResultsContainer.tsx
Fix for #4122.
Since the details list web component is always reloaded when making a selection it would always be scrolled to the top.
This fix implements initial scrolling to the same position on reload as it was in when making the selection. It also implements better support for keyboard selections which there was very limited support for before.
> Implement handling of scrolling after selection

- search-extensibility/src/models/layouts/ILayout.ts
- search-parts/package-lock.json
- search-parts/package.json
- search-parts/src/helpers/LayoutHelper.ts
- search-parts/src/layouts/results/detailsList/DetailListLayout.ts
- search-parts/src/webparts/searchFilters/SearchFiltersWebPart.ts
- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
Fixes an issue that would occur when enabling results grouping in the details list layout for a newly added results webpart. After adding a results webpart and switching to details list layout the grouping toggle was did not change state until you first exited webpart properties and then edited it again.
> Fix for enabling results grouping for newly added results webpart

- search-parts/src/components/DetailsListComponent.tsx
This fixes #4168 (discussed in #4157)
> Details List: Provide full search-results context in column expressions

- search-parts/src/helpers/DataFilterHelper.ts
See https://github.com/SharePoint/sp-dev-docs/issues/9098
When using a YesNo type refiner, the tokens ǂǂ54727565 and ǂǂ46616c7365 do not work. In this case, I replace the tokens with the values true and false. Feel free to modify my code 👋
> replace refinableyesno token

- search-parts/gulpfile.js
- search-parts/package-lock.json
- search-parts/package.json
- search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
Removes the default loading of html files and adds non-minimized loading of those to handle the handlebars templates correctly. Also bumps html-loader to be the same version as in SPFx 1.20.
Addresses #4220
> Add correct loading of handlebars templates

- docs/extensibility/extensibility_compatibility_matrix.md
- docs/extensibility/index.md
- mkdocs.yml
The idea behind this pull request is to list for all PnP Modern Search release, the SPFx version it uses so it is easier to know which version to use when developing extensibility projects (easier than looking directly at the source code).
> Add compatibility matrix for extensibility projects

- docs/extensibility/templating.md
Small typo in the html structure of the getAttachments helper.
The closing html tag containts href while the element is an '< a >'
> Update templating.md - fixing html error
