search-parts/src/services/SearchService/SearchService.ts
Check for RefinableDateSingle managed properties in search service
=> Don't ignore RefinableDateSingle refiners

search-extensibility-library/src/libraries/CustomSuggestionProvider.ts, search-extensibility-library/src/models/ISuggestion.ts, search-extensibility-library/src/models/SuggestionType.ts, search-parts/src/models/ISuggestionPerson.ts
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| New sample?      | no
| Related issues?  | n/a
Synchronize the ISuggestion interface from the base search-parts project to search-extensibility-library. Remove unused code files. Update sample suggestion provider.
@FranckyC - This is a small PR to cleanup leftover code from adding custom query suggestions.
=> Code cleanup; update suggestion provider extensibility sample

search-parts/src/components/DocumentCardComponent.tsx, search-parts/src/services/TemplateService/BaseTemplateService.tsx
**Fixed**:
- Fixed #18 regarding text encoding in the persona layout.
=> [search-parts] Bug Fix for #18 

search-parts/src/components/DocumentCardComponent.tsx, search-parts/src/controls/PreviewContainer/PreviewContainer.tsx, search-parts/src/services/TemplateService/BaseTemplateService.tsx, search-parts/src/templates/layouts/simple-list.html, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
- Added the ability to preview image files using the `getpreview.ashx` handler.
=> [search-parts] Fixed #69

search-parts/src/webparts/searchBox/SearchBoxWebPart.ts
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | n/a
The URL will now update when the search query is changed in the Search Box. This will only happen when the Search Box has dynamic data enabled and uses the URL hash or a query string parameter. The dynamic data configuration is detected when a search executes and the URL history is updated accordingly.
=> Search Queries update URL when Dynamic Data is Enabled

search-parts/src/services/UserService/UserService.ts, search-parts/src/webparts/searchRefiners/components/Templates/Persona/PersonaTemplate.tsx
=> Use claim and account name instead of email in Persona refiner

search-parts/src/templates/layouts/simple-list.html, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
Fixes regarding the extensibility library to be backward compatible with the upcoming release.
=> [search-parts] Quick bug fixes

search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer/SearchVerticalsContainer.module.scss, search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer/SearchVerticalsContainer.tsx
Force Pivot element to wrap items to next line
=> Allow search verticals to wrap

search-parts/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx
Hide the Web Part title as well when the 'Show blank' flag is set. Related to #132.
=> [search-parts] Hide the Web Part title as well when the 'Show blank' flag is set

search-parts/src/components/DocumentCardComponent.tsx, search-parts/src/services/TemplateService/BaseTemplateService.tsx, search-parts/src/templates/layouts/simple-list.html, search-parts/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx
Added a default image when thumbnail is not available (404). Related to #135.
=> [search-parts] Added a default image when thumbnail is not available (404)

search-parts/src/services/SearchService/SearchService.ts
=> [search-parts] Added the logic to resolve tolens in the query template field for search verticals

search-parts/src/webparts/searchRefiners/components/SearchRefinersContainer/SearchRefinersContainer.tsx, search-parts/src/webparts/searchRefiners/components/Templates/Checkbox/CheckboxTemplate.tsx, search-parts/src/webparts/searchRefiners/components/Templates/ContainerTree/ContainerTreeTemplate.tsx, search-parts/src/webparts/searchRefiners/components/Templates/FileType/FileTypeTemplate.tsx, search-parts/src/webparts/searchRefiners/components/Templates/Persona/PersonaTemplate.tsx
Fixed #151 as pointed out by @joelfmrodrigues .
=> [search-parts] Updated references to RefinementName to RefinementValue instead

search-parts/src/models/IRefinerConfiguration.ts, search-parts/src/webparts/searchRefiners/SearchRefinersWebPart.ts, search-parts/src/webparts/searchRefiners/components/Layouts/LinkPanel/LinkPanel.tsx, search-parts/src/webparts/searchRefiners/components/Layouts/Vertical/Vertical.tsx, search-parts/src/webparts/searchRefiners/components/Templates/Checkbox/CheckboxTemplate.module.scss, search-parts/src/webparts/searchRefiners/components/Templates/Checkbox/CheckboxTemplate.tsx, search-parts/src/webparts/searchRefiners/components/Templates/ContainerTree/ContainerTreeTemplate.module.scss, search-parts/src/webparts/searchRefiners/components/Templates/ContainerTree/ContainerTreeTemplate.tsx, search-parts/src/webparts/searchRefiners/components/Templates/DateRange/DateRangeTemplate.module.scss, search-parts/src/webparts/searchRefiners/components/Templates/DateRange/DateRangeTemplate.tsx, search-parts/src/webparts/searchRefiners/components/Templates/FileType/FileTypeTemplate.module.scss, search-parts/src/webparts/searchRefiners/components/Templates/FileType/FileTypeTemplate.tsx, search-parts/src/webparts/searchRefiners/components/Templates/FixedDateRange/FixedDateRangeTemplate.module.scss, search-parts/src/webparts/searchRefiners/components/Templates/FixedDateRange/FixedDateRangeTemplate.tsx, search-parts/src/webparts/searchRefiners/components/Templates/IBaseRefinerTemplateProps.ts, search-parts/src/webparts/searchRefiners/components/Templates/IBaseRefinerTemplateState.ts, search-parts/src/webparts/searchRefiners/components/Templates/Persona/PersonaTemplate.module.scss, search-parts/src/webparts/searchRefiners/components/Templates/Persona/PersonaTemplate.tsx, search-parts/src/webparts/searchRefiners/components/Templates/TemplateRenderer.tsx, search-parts/src/webparts/searchRefiners/loc/en-us.js, search-parts/src/webparts/searchRefiners/loc/es-es.js, search-parts/src/webparts/searchRefiners/loc/fr-fr.js, search-parts/src/webparts/searchRefiners/loc/mystrings.d.ts, search-parts/src/webparts/searchRefiners/loc/nl-nl.js
**What's in this Pull Request?**
Refinement value filters added to reduce the number of refinement values shown to the user
**Related issue**
Implements #145
=> Add refinement value filters to each template

docs/search-parts/getting-started.md
Replaced 'Thissolution' by 'This solution'
=> Fixed typo

search-parts/package-lock.json, search-parts/src/webparts/searchVerticals/ISearchVerticalsWebPartProps.ts, search-parts/src/webparts/searchVerticals/SearchVerticalsWebPart.ts, search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer/ISearchVerticalsContainerProps.ts, search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer/SearchVerticalsContainer.tsx, search-parts/src/webparts/searchVerticals/loc/en-us.js, search-parts/src/webparts/searchVerticals/loc/es-es.js, search-parts/src/webparts/searchVerticals/loc/fr-fr.js, search-parts/src/webparts/searchVerticals/loc/mystrings.d.ts, search-parts/src/webparts/searchVerticals/loc/nl-nl.js
Hi all,
I've updated the search vertical webpart to give users the possibility to define which search vertical they want to have selected by default. This works depending on a querystring parameter. The value of a given querystring parameter key (configurable in the webpart) will be matched with the current configured search verticals (by property 'tabName'). If a match is found the search vertical will be selected by default. If no match is found the first search vertical will be selected.
If you've got any additional questions/remarks feel free to ask.
Thx!
Regards,
Bart
=> Default search vertical

search-parts/src/templates/layouts/default.html
After the replacing of de the pagination web part by a web component, the pagination configuration was forgotten in the Custom layout (default.html)
=> [search-parts] template : added missing pagination configuration

docs/search-parts/templating.md, search-parts/src/services/TemplateService/BaseTemplateService.tsx, search-parts/src/services/TemplateService/LoadHelper.ts
Fixed documentation on fabric icon usage
=> #171 Improved fabric icon loading

docs/search-parts/templating.md
=> Added link to search custom renderer solution

docs/search-custom-renderer/getting-started.md
Currently goes to several redirects/has moved referrers before getting lost :)
=> Updating React Search Refiners links

search-parts/src/components/DetailsListComponent.tsx, search-parts/src/components/SliderComponent.tsx, search-parts/src/services/TemplateService/BaseTemplateService.tsx, search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer/SearchVerticalsContainer.tsx
Fixed #175. The init preview method was not called in details list and slider components.
=> [search-parts] Fixed 175. The preview was not working in custom details list.

search-parts/src/webparts/searchResults/components/SortPanel/SortPanel.tsx
My commits were based on https://github.com/microsoft-search/pnp-modern-search/pull/183
Fix for this issue https://github.com/microsoft-search/pnp-modern-search/issues/214
=> Fix for the issue sort direction is wrong when change sort column #214

search-parts/src/services/SearchService/SearchService.ts, search-parts/src/webparts/searchVerticals/SearchVerticalsWebPart.ts, search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer/SearchVerticalsContainer.tsx, search-parts/src/webparts/searchVerticals/loc/en-us.js, search-parts/src/webparts/searchVerticals/loc/es-es.js, search-parts/src/webparts/searchVerticals/loc/fr-fr.js, search-parts/src/webparts/searchVerticals/loc/mystrings.d.ts, search-parts/src/webparts/searchVerticals/loc/nl-nl.js
Fixed issue #250 regarding search verticals count.
=> [search-parts] Fixed #250

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
=> Updated the PR template

search-parts/src/controls/PreviewContainer/PreviewContainer.tsx, search-parts/src/services/TemplateService/BaseTemplateService.tsx, search-parts/src/services/TemplateService/TemplateService.ts, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
Fixes #273 #274 
Replaces #275
=> Fixes #273 #274

search-parts/src/models/ISearchResult.ts, search-parts/src/services/SearchService/SearchService.ts, search-parts/src/services/TemplateService/BaseTemplateService.tsx
Added Shortcut URL to Search Result
Created Aync function to get Shrotcut URLs in batch
Updated Search Results to add Shortcut URLs for results that are URL FileType
Updated getUrl handlebar helper to return ShortcutUrl for URL FileTypes
=> Added Batch call to get ShortCut URL for .url filetypes

search-parts/src/services/SearchService/SearchService.ts
Fixed bug created by PR #271.
@FranckyC  - Here is the null check fix for the FileType addition and bug I created with the previously merged PR.
=> Added FileType null check

search-parts/src/webparts/searchBox/SearchBoxWebPart.ts, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
=> Fixes #325

package-lock.json, search-parts/package-lock.json, search-parts/package.json, search-parts/src/webparts/searchBox/SearchBoxWebPart.ts, search-parts/src/webparts/searchRefiners/SearchRefinersWebPart.ts, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts, search-parts/src/webparts/searchVerticals/SearchVerticalsWebPart.ts
Turn off PnPTelemetry by default for all Web Parts #315.
=> [search-parts] Fixed #315 - Turn off PnPTelemetry by default

search-parts/src/webparts/searchResults/components/Layouts/SearchResultsTemplate.tsx
=> Fix script injection in templates on attributes

search-parts/src/webparts/searchRefiners/components/Templates/Persona/PersonaTemplate.tsx
https://github.com/microsoft-search/pnp-modern-search/issues/422
=> fix to handle userInfo is undefined when user is disabled

search-parts/src/webparts/searchResults/components/SearchResultsContainer/SearchResultsContainer.tsx
=> Fix for sort clearing on pagination

docs/search-parts/templating.md
Fixed broken link to handlebarsjs partials.
=> Fixed broken link to handlebarsjs partials

search-parts/src/styles/Common.module.scss
Fix the styling in display mode
=> Fix webpart title in display mode

docs/getting_started/connections_chart.md, docs/index.md, docs/usage/search-filters/index.md, docs/usage/search-results/connections/index.md, docs/usage/search-results/layouts/debug.md, docs/usage/search-verticals/index.md, search-extensibility/src/models/dataSources/IDataContext.ts, search-parts/src/models/common/ITemplateContext.ts, search-parts/src/webparts/searchFilters/loc/en-us.js, search-parts/src/webparts/searchResults/ISearchResultsWebPartProps.ts, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts, search-parts/src/webparts/searchVerticals/ISearchVerticalsWebPartProps.ts, search-parts/src/webparts/searchVerticals/loc/en-us.js
=> Update index doc

docs/installation.md, search-parts/config/package-solution.json
Updated to include all graph scopes
=> Updated install steps

search-parts/src/helpers/ObjectHelper.ts, search-parts/src/services/tokenService/TokenService.ts
Fixed an issue where the multi taxonomy or choice fields were not processed correctly.
=> Fixed #656 - V4 Search KQL token translation

search-parts/src/loc/da-dk.js, search-parts/src/webparts/searchBox/loc/da-dk.js, search-parts/src/webparts/searchFilters/loc/da-dk.js, search-parts/src/webparts/searchResults/loc/da-dk.js, search-parts/src/webparts/searchVerticals/loc/da-dk.js
Added Danish language support to the webparts.
=> Added danish translation

search-parts/src/layouts/results/cards/cards.html, search-parts/src/layouts/results/debug/results-debug.html, search-parts/src/layouts/results/detailsList/details-list.html, search-parts/src/layouts/results/people/people.html, search-parts/src/layouts/results/simpleList/simple-list.html
=> #756 - Added a condition to templates to hide page number if there is only one page.

search-parts/src/controls/TemplateRenderer/TemplateRenderer.scss, search-parts/src/layouts/results/simpleList/simple-list.html, search-parts/src/services/searchService/SharePointSearchService.ts
Fix css and promoted result template
=> #811 Set promoted even if primary is empty

.github/config.yml, search-parts/src/components/DetailsListComponent.tsx
#849 - Fixed an issue on the DetailsList when grouping. Item were not sorted before the grouping operation resulting to incorrect group indexes.
=> #846 - Fixed an issue on the DetailsList when grouping

search-parts/src/common/BaseWebPart.ts, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
Fixed issue regarding result types
=> Fixed #887

search-parts/src/loc/sv-SE.js, search-parts/src/webparts/searchBox/loc/sv-SE.js, search-parts/src/webparts/searchFilters/loc/sv-SE.js, search-parts/src/webparts/searchResults/loc/sv-SE.js, search-parts/src/webparts/searchVerticals/loc/sv-SE.js
No Swedish translation existed
Added Swedish translation
None.
=> Added Swedish language support

search-parts/src/dataSources/SharePointSearchDataSource.ts
Needed to ensure listitem URL's use path.
=> #945 Add contentclass to default properties/slots

docs/how-to-contribute.md
This PR includes more detail about the steps to perform to build the solution locally and should fix #725
=> Add more clarity to the contribution documentation

docs/extensibility/web_components_list.md
Anchor links at the top of the page were incorrect.
=> Fixed anchor links

search-parts/src/helpers/UrlHelper.ts
=> fix(searchBox): search terms URL encode

search-parts/src/services/SearchService/SearchService.ts
Update SearchService.ts to check for valid token before trying to retrieve file  url
=> Fix for issue 1121

search-parts/config/config.json, search-parts/src/components/PanelComponent.tsx, search-parts/src/layouts/filters/panel/panel.html
Added a temporary session storage variable for panel open state + fixed externals in config.json preventing using the WPs in de v mode.
=> Fixed #1144. Added a temporary session storage variable for panel open state

docs/scenarios/page-with-filters.md
=> Fixed images - resolves issue #1156

search-parts/src/components/filters/FilterComboBoxComponent.tsx
Used  dedicated state properties for options and selected keys in the Combo Box filter.
=> Fixed #1165

search-parts/src/dataSources/MicrosoftSearchDataSource.ts, search-parts/src/dataSources/SharePointSearchDataSource.ts
Filter out potentially empty field values
=> Allow pasting of properties with comma list

search-parts/src/components/FileIconComponent.tsx, search-parts/src/components/FilePreviewComponent.tsx, search-parts/src/dataSources/MicrosoftSearchDataSource.ts, search-parts/src/dataSources/SharePointSearchDataSource.ts, search-parts/src/services/searchService/SharePointSearchService.ts, search-parts/src/webparts/searchResults/components/SearchResultsContainer.tsx
=> Fix preview for folders and fix icon for onenote's

search-parts/src/controls/TemplateRenderer/TemplateRenderer.scss, search-parts/tsconfig.json
=> Fixed #1329 Cards template with odd numbers

search-parts/src/services/templateService/TemplateService.ts
=> Check if _webPartServiceScopes is defined

search-parts/src/components/DetailsListComponent.tsx, search-parts/src/components/FileIconComponent.tsx, search-parts/src/dataSources/SharePointSearchDataSource.ts, search-parts/src/layouts/results/simpleList/simple-list.html, search-parts/src/services/templateService/TemplateService.ts, search-parts/src/webparts/searchResults/components/SearchResultsContainer.tsx
* Removed thumbnail for a site result
* Use SiteLogo if present as the icon
=> #1348 Fix preview and icon for site results in list template

search-parts/src/loc/nb-no.js, search-parts/src/webparts/searchBox/loc/nb-no.js, search-parts/src/webparts/searchFilters/loc/nb-no.js, search-parts/src/webparts/searchResults/loc/nb-no.js, search-parts/src/webparts/searchVerticals/loc/nb-no.js
=> Add norwegian translation

search-parts/src/common/BaseWebPart.ts, search-parts/src/loc/commonStrings.d.ts, search-parts/src/loc/da-dk.js, search-parts/src/loc/en-us.js, search-parts/src/loc/fr-fr.js, search-parts/src/loc/nb-no.js, search-parts/src/loc/nl-nl.js, search-parts/src/loc/pl-pl.js, search-parts/src/loc/sv-SE.js, search-parts/src/webparts/searchFilters/ISearchFiltersWebPartProps.ts, search-parts/src/webparts/searchFilters/SearchFiltersWebPart.ts, search-parts/src/webparts/searchFilters/loc/da-dk.js, search-parts/src/webparts/searchFilters/loc/en-us.js, search-parts/src/webparts/searchFilters/loc/fr-fr.js, search-parts/src/webparts/searchFilters/loc/mystrings.d.ts, search-parts/src/webparts/searchFilters/loc/nb-no.js, search-parts/src/webparts/searchFilters/loc/nl-nl.js, search-parts/src/webparts/searchFilters/loc/pl-pl.js, search-parts/src/webparts/searchFilters/loc/sv-SE.js, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
New option to connect a search filters WP to a search vertical WP.
=> [Search Filters] Added the ability to connect a search filters Web Part to a vertical

search-parts/src/common/Constants.ts, search-parts/src/webparts/searchResults/ISearchResultsWebPartProps.ts, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts, search-parts/src/webparts/searchResults/loc/da-dk.js, search-parts/src/webparts/searchResults/loc/en-us.js, search-parts/src/webparts/searchResults/loc/fr-fr.js, search-parts/src/webparts/searchResults/loc/mystrings.d.ts, search-parts/src/webparts/searchResults/loc/nb-no.js, search-parts/src/webparts/searchResults/loc/nl-nl.js, search-parts/src/webparts/searchResults/loc/pl-pl.js, search-parts/src/webparts/searchResults/loc/sv-SE.js
The telemetry is on by default.
=> [Search Results] Added a toggle in the property to turn on/off the PnP telemetry (application insights)

search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
=> Bugfix: "useVerticals" and not "useFilters" property

search-parts/src/webparts/searchBox/SearchBoxWebPart.ts, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
Copy search box logic on query param parse to result web part.
=> #1550 Check that param is in place

search-parts/src/helpers/DynamicPropertyHelper.ts, search-parts/src/webparts/searchBox/SearchBoxWebPart.ts, search-parts/src/webparts/searchFilters/SearchFiltersWebPart.ts, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
Add try/catch and check on all dynamic data calls.
=> Possible fix for #1483

search-parts/src/webparts/searchFilters/loc/fr-fr.js
Fixed missing FR translations #1662
=> Fixed #1662

search-parts/src/components/filters/FilterComboBoxComponent.tsx
Fixed #1660 by moving Apply/Clear buttons on top of the combo box.
=> Fixed #1660

search-parts/src/helpers/ObjectHelper.ts
Updated the ObjectHelper,byPath method to handle wrong expression correctly
=> Updated ObjectHelper byPath

search-parts/src/services/tokenService/TokenService.ts
Updated the token logic for `{Site}` and `{User}` tokens. If the token property is not found in the current context (client side resolution) then the value is let untouched for server side processing as a query variable + restricted manual character escape to curly braces only.
=> Fixed #1769

search-parts/src/components/filters/FilterComboBoxComponent.tsx
Combo box search filter is now case insensitive
=> Fixed #1943

docs/extensibility/index.md
Added note in documentation about SPFx version for extensions
=> Fixed #1893

search-parts/src/components/DetailsListComponent.tsx, search-parts/src/services/templateService/TemplateService.ts
=> #1965 Added `properties` and `utils` from the main context to the Details List and Cards Handlebars context

search-parts/src/webparts/searchBox/SearchBoxWebPart.ts
Fixed #1840 added a conditional check for the data source reference property
=> Fixed #1840

search-parts/src/loc/es-es.js, search-parts/src/webparts/searchBox/loc/es-es.js, search-parts/src/webparts/searchFilters/loc/es-es.js, search-parts/src/webparts/searchResults/loc/es-es.js, search-parts/src/webparts/searchVerticals/loc/es-es.js
=> Adding Spanish translation

search-parts/src/helpers/UrlHelper.ts, search-parts/src/layouts/resultTypes/default_simple_list.html, search-parts/src/layouts/results/simpleList/simple-list.html, search-parts/src/services/templateService/TemplateService.ts, search-parts/src/services/tokenService/TokenService.ts
=> Resolve issues from #1803

docs/usage/search-box/index.md, docs/usage/search-results/tokens.md, search-parts/src/webparts/searchBox/components/SearchBoxContainer.tsx
As suggested by @edarroudi in #2055
=> #2055 Allow tokens in "Send the query to a new page/ Property Page URL"

search-parts/src/webparts/searchBox/SearchBoxWebPart.manifest.json, search-parts/src/webparts/searchFilters/SearchFiltersWebPart.manifest.json, search-parts/src/webparts/searchVerticals/SearchVerticalsWebPart.manifest.json
=> Support fullbleed for all parts

search-parts/config/package-solution.json, search-parts/src/dataSources/MicrosoftSearchDataSource.ts
From https://docs.microsoft.com/en-us/graph/search-concept-chat-messages
=> Added Teams messages entity type option for Microsoft search data source

search-parts/src/loc/pt-br.js, search-parts/src/webparts/searchBox/loc/pt-br.js, search-parts/src/webparts/searchFilters/loc/pt-br.js, search-parts/src/webparts/searchResults/loc/pt-br.js, search-parts/src/webparts/searchVerticals/loc/en-us.js, search-parts/src/webparts/searchVerticals/loc/pt-br.js
Created the localization files to pt-br:
1. search-parts/src/loc/pt-br.js
2. search-parts/src/webparts/searchBox/loc/pt-br.js
3. search-parts/src/webparts/searchFilters/loc/pt-br.js
4. search-parts/src/webparts/searchResults/loc/pt-br.js
5. search-parts/src/webparts/searchVerticals/loc/pt-br.js
Fixed the spell of word 'visibility' in search-parts/src/webparts/searchVerticals/loc/en-us.js (line 17)
=> Creating pt-br localization files and correct en-us file.

search-parts/src/dataSources/SharePointSearchDataSource.ts
Might help for #1254 and #596.
=> Disable interleaving when using query rules.

docs/how-to-contribute.md
Removed an extra "to" which I thought to be a typo.
=> Removed a Typo

search-parts/src/webparts/searchFilters/components/SearchFiltersContainer.tsx
as requested @wobba
Fixed count due to deep links calculated last.
See #2534
=> [Fix] Filter count bug due to PR2503

search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
Added Microsoft Graph Toolkit option for adaptive cards layout
=> Added Microsoft Graph Toolkit option for adaptive cards layout

docs/extensibility/custom_query_modifications.md, docs/extensibility/index.md, docs/index.md, mkdocs.yml
I checked the md files and there were some small mistakes.
Also the nav link to custom data sources was wrong
=> Small documentation corrections

search-parts/src/helpers/GraphToolKitHelper.ts, search-parts/src/layouts/results/people/PeopleLayout.ts, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
=> Fix for #2140

.github/ISSUE_TEMPLATE/bug_report.md, docs/extensibility/templating.md, search-parts/.vscode/extensions.json, search-parts/src/controls/TemplateRenderer/TemplateRenderer.tsx
- Support for [@layer](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_layers) added
- Documentation update
- Remove of deprecated Chrome VS Code plugin
- Refactor of CSS handling
=> @layer support added for search result styles

search-parts/src/models/common/ITemplateContext.ts, search-parts/src/webparts/searchResults/SearchResultsWebPart.manifest.json, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts, search-parts/src/webparts/searchResults/components/ISearchResultsContainerProps.ts, search-parts/src/webparts/searchResults/components/SearchResultsContainer.tsx
=> Support result web part as Teams app with SPFx Teams Context exposed

search-parts/src/webparts/searchFilters/SearchFiltersWebPart.ts, search-parts/src/webparts/searchFilters/loc/da-dk.js, search-parts/src/webparts/searchFilters/loc/de-de.js, search-parts/src/webparts/searchFilters/loc/en-us.js, search-parts/src/webparts/searchFilters/loc/es-es.js, search-parts/src/webparts/searchFilters/loc/fi-fi.js, search-parts/src/webparts/searchFilters/loc/fr-fr.js, search-parts/src/webparts/searchFilters/loc/nb-no.js, search-parts/src/webparts/searchFilters/loc/nl-nl.js, search-parts/src/webparts/searchFilters/loc/pl-pl.js, search-parts/src/webparts/searchFilters/loc/pt-br.js, search-parts/src/webparts/searchFilters/loc/sv-SE.js, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts, search-parts/src/webparts/searchResults/loc/da-dk.js, search-parts/src/webparts/searchResults/loc/de-de.js, search-parts/src/webparts/searchResults/loc/en-us.js, search-parts/src/webparts/searchResults/loc/es-es.js, search-parts/src/webparts/searchResults/loc/fi-fi.js, search-parts/src/webparts/searchResults/loc/fr-fr.js, search-parts/src/webparts/searchResults/loc/nb-no.js, search-parts/src/webparts/searchResults/loc/nl-nl.js, search-parts/src/webparts/searchResults/loc/pl-pl.js, search-parts/src/webparts/searchResults/loc/pt-br.js, search-parts/src/webparts/searchResults/loc/sv-SE.js
=> Allow .txt files as external template files for filter/result web part

search-parts/src/webparts/searchFilters/components/SearchFiltersContainer.tsx
=> Allow to clear as long as one value is picked

docs/usage/search-results/tokens.md, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
=> Don't replace {searchTerms} if empty

search-parts/src/components/filters/FilterDateRangeComponent.tsx, search-parts/src/helpers/DataFilterHelper.ts
=> #1601 Made date range include start and end date

search-parts/src/dataSources/MicrosoftSearchDataSource.ts, search-parts/src/dataSources/SharePointSearchDataSource.ts, search-parts/src/services/searchService/SharePointSearchService.ts
=> Added deephits parameter to refiners

search-parts/src/components/DetailsListComponent.tsx, search-parts/src/components/DocumentCardComponent.tsx, search-parts/src/components/ItemSelectionComponent.tsx
Fixes #2291, and fixes bug where card select was not working.
=> Improve focus on item selection

search-parts/src/helpers/ObjectHelper.ts
Optimized objecthelper.bypath
Fixes #2242
=> #2242 Support props starting with a number in slots

search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
=> Remove padding if hide on no result

search-parts/src/dataSources/SharePointSearchDataSource.ts, search-parts/src/webparts/searchResults/components/SearchResultsContainer.tsx
=> Prefer thumbnailurl if present

search-parts/src/services/templateService/TemplateService.ts
=> Make guid regx better

search-parts/src/components/DetailsListComponent.tsx
=> Remove click handler for icon

search-parts/src/helpers/DataFilterHelper.ts
=> Fix for number tokens in refinement strings

docs/index.md, docs/using-query-tools-to-verify-issues.md
Simple update of the contributors names and companies + added two links to videos about using SP Query tool and SP Editor for debugging before creating an issue
=> Update contributers + new video for verification

docs/usage/search-results/tokens.md, search-parts/src/services/tokenService/TokenService.ts
=> Added more date/time tokens

search-parts/src/helpers/UrlHelper.ts, search-parts/src/webparts/searchBox/components/SearchBoxContainer.tsx
=> #3089 Don't append hash on redirect with query param

search-parts/config/package-solution.json, search-parts/package-lock.json, search-parts/package.json, search-parts/src/helpers/DateHelper.ts
=> Fix localized SharePoint page when English is secondary language

search-parts/src/layouts/results/cards/cards.html, search-parts/src/layouts/results/detailsList/details-list.html, search-parts/src/layouts/results/people/people.html, search-parts/src/layouts/results/slider/slider.html, search-parts/src/services/templateService/TemplateService.ts
Regarding #2972 
I reworked how the truncation works, that it just drops items and uses destructuring.
=> Context truncation

search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer.tsx
=> Encode query for vertical links

search-parts/src/components/PaginationComponent.module.scss
=> Fix colors for inverted theme

search-parts/src/controls/PreviewContainer/PreviewContainer.tsx
=> #3328 Remove callout on close

search-parts/src/helpers/DateHelper.ts
=> #3304 rework locale logic

docs/scenarios/index.md
The title and link to the scenario ## [Use query string from url for dynamic results](use-query-string-in-url.md) was missing.
=> Update scenario index.md

search-parts/src/components/filters/FilterCheckBoxComponent.tsx, search-parts/src/components/filters/FilterSearchBoxComponent.module.scss
Fix selected filter tag text color and ensure checked state of radio button is applied. Applies to #3421.
=> Fix taxonomy filters selected tag color and radio button checked state

search-parts/src/webparts/searchFilters/loc/da-dk.js, search-parts/src/webparts/searchResults/loc/da-dk.js, search-parts/src/webparts/searchVerticals/loc/da-dk.js
minor updates to the da-dk translation files
=> Update Danish localization strings

search-parts/src/loc/de-de.js, search-parts/src/webparts/searchBox/loc/de-de.js, search-parts/src/webparts/searchFilters/loc/de-de.js, search-parts/src/webparts/searchResults/loc/de-de.js, search-parts/src/webparts/searchVerticals/loc/de-de.js
Fixed some typos and reworked texts in German localization files.
=> Fixed some typos and texts in German localization files

search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer.tsx
=> Fix for selecting vertical using query string

search-parts/src/components/DetailsListComponent.tsx
Seems to have been a merge mistake from my side in my latest PR, sorry for that.
=> Fix imports in DetailsListComponent

search-parts/src/common/Constants.ts
see https://github.com/microsoft-search/pnp-modern-search/issues/3617
=> add msteams to list of allowed uri protocols

search-parts/src/components/DetailsListComponent.tsx
=> Render empty string instead of null and undefined values

search-parts/src/webparts/searchFilters/components/SearchFiltersContainer.tsx
Fixing #3656
Check whether there are applied filters. If no - remove query string. If yes - update query string
=> Do not clear query string if there are applied filters

docs/extensibility/templating.md
Converted large Handlebars helpers table into paragraphs with headers (for anchor links)
Reordered helpers alphabetically
General formatting and grammar fixes
Fixes #3680
=> Updates to Templating.md

search-parts/src/components/DownloadSelectedItemsButtonComponent.tsx
Fixes an issue that occured when downloading multiple files that are located in a folder.
=> Fix download when files are in a folder

search-parts/src/components/DetailsListComponent.tsx
Implements a new method of rendering sticky headers in details list layout. Fix for #3747.
=> New method of rendering sticky headers

search-parts/package-lock.json, search-parts/src/webparts/searchBox/SearchBoxWebPart.ts, search-parts/src/webparts/searchFilters/SearchFiltersWebPart.ts, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
=> Fix for web part edit

search-parts/src/loc/it-it.js, search-parts/src/webparts/searchBox/SearchBoxWebPart.manifest.json, search-parts/src/webparts/searchBox/loc/it-it.js, search-parts/src/webparts/searchFilters/SearchFiltersWebPart.manifest.json, search-parts/src/webparts/searchFilters/loc/it-it.js, search-parts/src/webparts/searchResults/SearchResultsWebPart.manifest.json, search-parts/src/webparts/searchResults/loc/it-it.js, search-parts/src/webparts/searchVerticals/SearchVerticalsWebPart.manifest.json, search-parts/src/webparts/searchVerticals/loc/it-it.js
This pull request includes the Italian translation of localization (loc) files and manifest.json files.
The goal is to provide an accurate and comprehensive Italian version of the Web Parts interface and its metadata.
**Changes Included:**
1. Localization Files (loc):
a. Translated all key-value pairs in the .loc files from English to Italian.
b. Ensured that all translations are contextually accurate and maintain the intended meaning.
2. Manifest Files (manifest.json):
a. Translated relevant sections of manifest.json files for all Web Parts to Italian.
b. Verified that all translated entries are correctly formatted according to JSON standards.
Related issue: #3792
=> Italian Translation of loc files and manifest.json files

docs/usage/search-verticals/index.md
Clarification in the docs on the required permissions for audience targeting.
=> Update audience docs

search-parts/src/loc/de-de.js
Updates for German strings for Filter operators
=> Updates for German strings for Filter operators

search-parts/src/webparts/searchResults/SearchResultsWebPart.ts, search-parts/src/webparts/searchResults/components/ISearchResultsContainerProps.ts, search-parts/src/webparts/searchResults/components/SearchResultsContainer.tsx
=> Fix for removing padding and margin if nothing to show

search-parts/src/webparts/searchBox/SearchBoxWebPart.ts, search-parts/src/webparts/searchFilters/SearchFiltersWebPart.ts, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts
=> Edit title fix

docs/installation.md, search-parts/config/package-solution.json
=> Fix for #3778

search-parts/package-lock.json, search-parts/package.json, search-parts/src/dataSources/MicrosoftSearchDataSource.ts, search-parts/src/dataSources/SharePointSearchDataSource.ts
=> Fix adaptive cards #4038

search-parts/src/components/DetailsListComponent.tsx, search-parts/src/components/DocumentCardComponent.tsx, search-parts/src/components/PersonaComponent.tsx, search-parts/src/controls/TemplateRenderer/TemplateRenderer.tsx, search-parts/src/services/templateService/ITemplateService.ts, search-parts/src/services/templateService/TemplateService.ts
Adds mgt disambiguation handling to a few places where it was missing:
- People card fields
- Document card fields
- Adaptive cards
Addresses #4167
=> Fix mgt disambiguation

docs/usage/search-results/layouts/index.md, search-parts/src/models/common/IItemSelectionProps.ts, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts, search-parts/src/webparts/searchResults/components/SearchResultsContainer.tsx, search-parts/src/webparts/searchResults/loc/da-dk.js, search-parts/src/webparts/searchResults/loc/de-de.js, search-parts/src/webparts/searchResults/loc/en-us.js, search-parts/src/webparts/searchResults/loc/es-es.js, search-parts/src/webparts/searchResults/loc/fi-fi.js, search-parts/src/webparts/searchResults/loc/fr-fr.js, search-parts/src/webparts/searchResults/loc/it-it.js, search-parts/src/webparts/searchResults/loc/mystrings.d.ts, search-parts/src/webparts/searchResults/loc/nb-no.js, search-parts/src/webparts/searchResults/loc/nl-nl.js, search-parts/src/webparts/searchResults/loc/pl-pl.js, search-parts/src/webparts/searchResults/loc/pt-br.js, search-parts/src/webparts/searchResults/loc/sv-SE.js
Adds a new setting for if the selection should be cleared when clicking outside of the selection zone.
Addresses #4212.
=> Add setting for preserving selection on empty click

search-parts/src/services/tokenService/TokenService.ts
=> Optimize TokenService to cache current hub site information and page properties

search-parts/src/loc/cs-cz.js, search-parts/src/webparts/searchBox/loc/cs-cz.js, search-parts/src/webparts/searchFilters/loc/cs-cz.js, search-parts/src/webparts/searchResults/loc/cs-cz.js, search-parts/src/webparts/searchVerticals/loc/cs-cz.js
Added Czech localization in `cs-cz` file as discussed in here [#4249](https://github.com/microsoft-search/pnp-modern-search/discussions/4249)
=> Added Czech localization

docs/extensibility/custom_layout.md, docs/extensibility/index.md
According to #4237 
(also updated the extensiblity example in [this repo](https://github.com/[microsoft-search/pnp-modern-search-extensibility-samples](https://github.com/microsoft-search/pnp-modern-search-extensibility-samples)) in a separate [PR](https://github.com/microsoft-search/pnp-modern-search-extensibility-samples/pull/22))
=> Updated description of steps for creating an extensibility library

search-parts/src/webparts/searchFilters/SearchFiltersWebPart.ts, search-parts/src/webparts/searchFilters/components/SearchFiltersContainer.tsx, search-parts/src/webparts/searchResults/SearchResultsWebPart.ts, search-parts/src/webparts/searchResults/components/SearchResultsContainer.tsx, search-parts/src/webparts/searchVerticals/SearchVerticalsWebPart.ts, search-parts/src/webparts/searchVerticals/components/SearchVerticalsContainer.tsx
Fix for [#4377](https://github.com/VictorRomanov1986/pnp-modern-search/issues/4377).
Reducing bundle size by importing individual components instead of the whole package
=> Fix for #4377. +Reducing bundle size
